# Generated by Django 3.0.2 on 2020-01-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenURL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
